### ISSUE TITLE
missing contact information

### ISSUE THREAD

**Issue by KrishMunot** [Azure/azure.github.io#45]
The url to the contact is missing or dir is dead - https://azure.github.io/guidelines/#contact

**Comment by devigned** [comment]
Seems to work for me. I clicked on the link and landed on the contact section of guidelines.

**Comment by hdost** [comment]
@devigned the link he put above leads to the section, but the button in that section leads to nowhere due to: https://github.com/Azure/azure.github.io/commit/0d0ca313d1a3d55b3fa230aa4fb7dc96b624173c#diff-07660dfaca2d788ed6ae6e2313b0e340
The link the button has is https://azure.github.io/contact/
Right now there's not option of who to contact. Unless I look at that commit :disappointed:

**Comment by jeffwilcox** [comment]
Recommend closing this issue as the site is likely going to redirect to the more up-to-date, official information on the docs.microsoft.com site.
